### ISSUE TITLE
How can I eval in Icdar 2015 format dataset

### ISSUE THREAD

**Issue by hoho303** [jylins/CORE-Text#3]
Thanh you for your excellent work. 
I am successfull in training custom dataset and get checkpoint file with Icdar 2015 format dataset. I want to evaluate testset with the same format of train dataset but get a error NoneType. I used core_pretrain config and custom dataset. 
How can I fix it.  Thank you very much!

![image](https://user-images.githubusercontent.com/31401629/145196268-beb6206a-1cf4-4daf-bf79-164e9cd5acff.png)

**Comment by rigvedsah000** [comment]
Hi, how did you solved above error?
